# Generated by Django 4.2 on 2023-05-11 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("relatorioapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Programacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=300)),
                ("descricao", models.CharField(max_length=3000)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("Noticia", "Notícia"),
                            ("Pesquisa", "Pesquisa"),
                            ("Relatorio", "Relatório"),
                        ],
                        max_length=50,
                    ),
                ),
                ("autor", models.CharField(blank=True, max_length=30, null=True)),
                ("data", models.DateField()),
                (
                    "paragrafo1",
                    models.CharField(blank=True, max_length=10000, null=True),
                ),
                (
                    "paragrafo2",
                    models.CharField(blank=True, max_length=10000, null=True),
                ),
                (
                    "paragrafo3",
                    models.CharField(blank=True, max_length=10000, null=True),
                ),
                (
                    "paragrafo4",
                    models.CharField(blank=True, max_length=10000, null=True),
                ),
                (
                    "paragrafo5",
                    models.CharField(blank=True, max_length=10000, null=True),
                ),
                ("arquivo", models.FileField(blank=True, null=True, upload_to="pdfs/")),
                (
                    "imagem_thumb",
                    models.ImageField(blank=True, null=True, upload_to="images_thumb/"),
                ),
                (
                    "imagem_post",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                (
                    "legenda_imagem",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
            ],
        ),
    ]
