# Generated by Django 4.1.7 on 2023-05-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorioapp', '0002_programacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programacao',
            name='tipo',
            field=models.CharField(choices=[('Noticia', 'Notícia'), ('Pesquisa', 'Pesquisa'), ('Relatorio', 'Relatório'), ('Pipacast', 'Pipacast')], max_length=50),
        ),
    ]
