# Generated by Django 4.1.7 on 2023-05-18 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relatorioapp', '0003_alter_programacao_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programacao',
            options={'verbose_name_plural': 'programacoes'},
        ),
        migrations.AlterModelOptions(
            name='relatorio',
            options={'verbose_name_plural': 'relatorio'},
        ),
    ]
