# Generated by Django 4.2 on 2023-05-22 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("relatorioapp", "0004_alter_programacao_options_alter_relatorio_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relatorio",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("Noticia", "Notícia"),
                    ("Pesquisa", "Pesquisa"),
                    ("Relatorio", "Relatório"),
                    ("Relatorio_de_audiencia", "Relatório de audiência"),
                ],
                max_length=50,
            ),
        ),
    ]
