# Generated by Django 4.2 on 2023-05-23 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("relatorioapp", "0005_alter_relatorio_tipo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relatorio",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("Noticia", "Notícia"),
                    ("Pesquisa", "Pesquisa"),
                    ("Outro", "Outro"),
                    ("Relatorio_de_audiencia", "Relatório de audiência"),
                ],
                max_length=50,
            ),
        ),
    ]
