# Generated by Django 4.2 on 2023-05-23 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("relatorioapp", "0006_alter_relatorio_tipo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="programacao",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("Noticia", "Notícia"),
                    ("Pesquisa", "Pesquisa"),
                    ("Pipacast", "Pipacast"),
                ],
                max_length=50,
            ),
        ),
    ]
