# Generated by Django 4.2 on 2023-05-25 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("relatorioapp", "0007_alter_programacao_tipo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="programacao",
            name="tipo",
            field=models.CharField(
                choices=[("Programacao", "Programação"), ("Pipacast", "Pipacast")],
                max_length=50,
            ),
        ),
    ]
