# Generated by Django 4.2 on 2023-05-25 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("relatorioapp", "0008_alter_programacao_tipo"),
    ]

    operations = [
        migrations.AddField(
            model_name="programacao",
            name="subtipo",
            field=models.CharField(
                choices=[("pdf", "pdf"), ("blog", "blog")],
                default="blog",
                max_length=50,
            ),
        ),
    ]
