# Generated by Django 4.2 on 2023-05-29 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("relatorioapp", "0010_programacao_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="Carrossel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "imagem_c_principal",
                    models.ImageField(upload_to="images_carrossel/"),
                ),
                (
                    "legenda_c_principal",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
            ],
        ),
    ]
