# Generated by Django 4.2 on 2023-05-29 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("relatorioapp", "0011_carrossel"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="carrossel",
            options={"verbose_name_plural": "carrossel"},
        ),
        migrations.RenameField(
            model_name="carrossel",
            old_name="legenda_c_principal",
            new_name="legenda_1",
        ),
        migrations.RemoveField(
            model_name="carrossel",
            name="imagem_c_principal",
        ),
        migrations.AddField(
            model_name="carrossel",
            name="imagem_principal",
            field=models.ImageField(
                blank=True, null=True, upload_to="images_carrossel/"
            ),
        ),
        migrations.AddField(
            model_name="carrossel",
            name="imagem_secundaria",
            field=models.ImageField(
                blank=True, null=True, upload_to="images_carrossel/"
            ),
        ),
        migrations.AddField(
            model_name="carrossel",
            name="legenda_2",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="carrossel",
            name="legenda_secundaria_1",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="carrossel",
            name="legenda_secundaria_2",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
